package com.dentalstack.doctor.enums.doctor;

public enum DoctorRole {
    CONSULTING_ORTHODONTIST,
    CLINIC_OWNER,
    IN_OFFICE_MANUFACTURER,
    ALIGNER_COMPANY_OR_LAB,
    COMMERCIAL_ALIGNER_LAB,
    LAB_STAFF,
    CUSTOMER,
    VENDOR,
    PRACTICE,
    ENTERPRISE_COMPANY_LAB,
    INTERNAL_USER,
    ENTERPRISE_CUSTOMER,
    GROWTH_CUSTOMER,
    PRACTICE_CUSTOMER
}
