server:
    port: 9200
    
spring:
    application:
        name: consumer-service
    profiles:
        active: prod
        
management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: when_authorized
            probes:
                enabled: true