spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://stage-ds-common-postgres.dental-stack.com:5432/auth_service_stage
    username: auth_service_stage
    password: 53@{<38UB£m&
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
      max-lifetime: 50000
      idle-timeout: 30000
      minimum-idle: 5
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:10000
          doctor-service:
            url: http://localhost:9000
          chat-service:
            url: http://localhost:9500
          patient-service:
            url: http://localhost:8900

dentalstack:
  jwt:
    secret:
      token: "ZilQ8bxNF+6meDFCUj+5UmfeBKdVCiI2HUqvRRCPRFio/pQaCIV4uvpiwaCJ4cnFIMgvXK8fYJyhnXau37U+lA=="
      validity_in_ms: 86400000 # 24 hours in milliseconds
      validity_in_ms_patient: 2592000000 # 30 days in milliseconds
    sso:
      validity_in_minutes: 5
    refresh:
      validity_in_hours: 24

synapse:
  base-url: https://synapsehealthtech.stage.dental-stack.com
