package com.dentalstack.patient.feature.aligner.entity.action;

public enum AlignerActionType {
    CHECK_IN,
    ALIGNER_CHANGE,
    FORCE_ALIGNER_CHANGE,
    ISSUE_REPORT,
    MOVE_TO_PREVIOUS_ALIGNER,
    ALL,
    MANUAl_ALIGNER_CHANGE,
    WEAR_DAYS_UPDATED,
    REMINDER_SENT_TO_PATIENT,
    TREATMENT_PAUSED,
    TREATMENT_RESUMED,
    ALIGNER_CHANGE_SCHEDULED,
    ALIGNER_CHANGE_PENDING_APPROVAL,
    CHECK_IN_PENDING_APPROVAL,
    ALIGNER_CHANGE_OVERDUE,
    AWAITING_RESUME_APPROVAL,
    TREATMENT_DEACTIVATED,
    CREATE_REFINEMENT_REMINDER,
    ALIGNER_CHANGE_OVERDUE_PENDING_ACTION
}
