export default {
  DASHBOARD: 'DASHBOARD',
  PATIENTS: 'PATIENTS',
  CHATS: 'CHATS',
  LAB_CHAT: 'LAB_CHAT',
  MORE: 'MORE',
  PRACTICES: 'PRACTICES',
  ORDERS: 'ORDERS',
  CUSTOMERS: 'CUSTOMERS',
} as const
