export default {
  ALIGNER_CHECK_IN_PENDING: 'ALIGNER_CHECK_IN_PENDING',
  MISSED_ALIGNER_CHANGE_DATE: 'MISSED_ALIGNER_CHANGE_DATE',
  UPCOMING_ALIGNER_CHANGE: 'UPCOMING_ALIGNER_CHANGE',
  POOR_COMPLIANCE: 'POOR_COMPLIANCE',
  GOOD_COMPLIANCE: 'GOOD_COMPLIANCE',
  ALL: 'ALL',
} as const
