export default {
  HOME: 'HOME',
  WORKSPACE: 'WORKSPACE',
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  LABEL_VIEW: 'LABEL_VIEW',
  PRACTICE_ORDER: 'PRACTICE_ORDER',
  CUSTOMER_ORDER: 'CUSTOMER_ORDER',
} as const
