export default {
  PERFECT_FIT: 'PERFECT_FIT',
  NOT_FITTING: 'NOT_FITTING',
  LOOSE_AT_BACK: 'LOOSE_AT_BACK',
  LOOSE_AT_FRONT: 'LOOSE_AT_FRONT',
  SHARP_EDGES: 'SHARP_EDGES',
  BROKEN_CRACKED_ALIGNER: 'BROKEN_CRACKED_ALIGNER',
  MISSING_ALIGNER: 'MISSING_ALIGNER',
  IRRITATION_TO_GUMS_OR_TONGUE: 'IRRITATION_TO_GUMS_OR_TONGUE',
  MISC: 'MISC',
} as const
