export default {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  NEED_MORE_INFO: 'NEED_MORE_INFO',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  RE_PLAN: 'RE_PLAN',
  COMPLETED: 'COMPLETED',

  ORDERED: 'ORDERED',
  REQUEST_REVISION: 'REQUEST_REVISION',
} as const
