export default {
  STEP_1_DOCTOR_DETAILS: 'STEP_1_DOCTOR_DETAILS',
  STEP_2_PRACTICE_LOCATION: 'STEP_2_PRACTICE_LOCATION',
  STEP_3_PRACTICE_LOCATION_DETAILS: 'STEP_3_PRACTICE_LOCATION_DETAILS',
  STEP_4_ADD_PATIENT: 'STEP_4_ADD_PATIENT',
  STEP_5_VIEW_PATIENT_DETAILS: 'STEP_5_VIEW_PATIENT_DETAILS',
  STEP_SUCCESS: 'STEP_SUCCESS',
  FINAL_STEP: 'FINAL_STEP',
  CLOSE_ON_BOARD: 'CLOSE_ON_BOARD',
} as const
