export default {
  ORDER_CREATED_NEW_TO_OLD: 'ORDER_CREATED_NEW_TO_OLD',
  ORDER_CREATED_OLD_TO_NEW: 'ORDER_CREATED_OLD_TO_NEW',
  LAST_UPDATED_NEW_TO_OLD: 'LAST_UPDATED_NEW_TO_OLD',
  LAST_UPDATED_OLD_TO_NEW: 'LAST_UPDATED_OLD_TO_NEW',
  NAME_ASC: 'NAME_ASC',
  NAME_DEC: 'NAME_DEC',
} as const
