export default {
  ALL: 'ALL',
  ASSESSMENT: 'ASSESSMENT',
  IN_PLANNING: 'IN_PLANNING',
  ADD_TRACKING: 'ADD_TRACKING',
  STARTING_SOON: 'STARTING_SOON',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETE',
  PAUSED: 'PAUSED',
  REFINEMENT: 'REFINEMENT',
  MANUFACTURING: 'MANUFACTURING',
  IN_TRANSIT: 'IN_TRANSIT',
  ALL_TREATMENT_TRACKING: 'ALL_TREATMENT_TRACKING',
} as const
