export default {
  UPGRADE_PLAN: 'UPGRADE_PLAN',
  RENEWAL_PLAN: 'RENEWAL_PLAN',
  TOP_UP_STORAGE: 'TOP_UP_STORAGE',
  TOP_UP_PATIENT: 'TOP_UP_PATIENT',
  BRACES_MODULE: 'BRACES_MODULE',
  GOOGLE_DRIVE_STORAGE: 'GOOGLE_DRIVE_STORAGE',
  WHATSAPP_NOTIFICATION: 'WHATSAPP_NOTIFICATION',
} as const
