export default {
  STUDENT: 'STUDENT',
  STARTER: 'STARTER',
  LITE: 'LITE',
  GROWTH: 'GROWTH',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE',
  DESIGN_LAB: 'DESIGN_LAB',
  COMMERCIAL_LAB_PLAN: 'COMMERCIAL_LAB_PLAN',
} as const
