export default {
  SET_UP_TREATMENT: 'SET_UP_TREATMENT',
  TREATMENT_SAVE_FOR_LATER: 'TREATMENT_SAVE_FOR_LATER',
  TREATMENT_FUTURE: 'TREATMENT_FUTURE',
  TREATMENT_STARTED: 'TREATMENT_STARTED',
  TREATMENT_COMPLETED: 'TREATMENT_COMPLETED',
  TREATMENT_DEACTIVATED: 'TREATMENT_DEACTIVATED',
  ASK_PATIENT_TO_FILL: 'ASK_PATIENT_TO_FILL',
} as const
