package com.dentalstack.patient.feature.calendar.dto;

public enum CalendarResponseTypes {
    STARTER_PLAN_EXPIRING,
    GROWTH_PLAN_EXPIRING,
    ALIGNER_CHECK_IN,
    ALIGNER_CHANGE_ON_TIME,
    MANUAL_TRACKING,
    RESUME_TREATMENT_REMINDER,
    ALIGNER_CHANGED,
    APPOINTMENT_REMINDER,
    APPOINTMENT,
    PRODUCTION_REMINDER,
    GENERAL_REMINDER,
    PAYMENT_REMINDER,
    PLAN,
    STUDENT_PLAN_EXPIRING,
    ENTERPRISE_PLAN_EXPIRING,
    PROFESSIONAL_PLAN_EXPIRING,
}
