spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://stage-ds-common-postgres.dental-stack.com:5432/patient_service_stage
    username: patient_service_stage
    password: 95\pNs{cs5
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      max-lifetime: 50000
      idle-timeout: 30000
      minimum-idle: 5
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:10000
          doctor-service:
            url: http://localhost:9000
          chat-service:
            url: http://localhost:9500
          patient-service:
            url: http://localhost:8900

app:
  cloud:
    amazon:
      s3:
        bucket:
          blog: dev-patient-gallery-ds
          gallery: dev-patient-gallery-ds
          faq: dev-patient-gallery-ds
          patient: dev-patient-gallery-ds


aws_access_key: AKIAQKKNKY3EICYDTHBQ
aws_secret_key: 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

aws.s3.bucket.name: prod-patient-gallery
aws.s3.bucket.region: Asia Pacific (Mumbai) ap-south-1