plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.1'
    id 'io.spring.dependency-management' version '1.1.3'

    id "com.diffplug.spotless" version "6.22.0"
}
group = 'com.dentalstack'
version = '0.0.1-SNAPSHOT'

java {
}

ext {
    set('springCloudVersion', "2022.0.0")
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'javax.validation:validation-api:2.0.1.Final'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework:spring-web'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.springframework.boot:spring-boot-starter-actuator:3.2.0'
    implementation 'org.springframework:spring-webmvc'
    implementation 'ch.qos.logback:logback-classic'
    implementation 'org.bouncycastle:bcprov-jdk15on:1.61'
    implementation 'org.jetbrains:annotations:23.0.0'


    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.0.13'
    implementation 'javax.validation:validation-api'
    implementation 'com.google.code.gson:gson:2.8.8'

    // Feign client
    implementation 'org.springframework.cloud:spring-cloud-starter-feign:1.4.7.RELEASE'
    implementation 'io.github.openfeign:feign-jackson:12.4'

    // https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api
    implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '3.0.2'

    implementation 'org.springframework.boot:spring-boot-starter-validation'

    //S3 service
    implementation 'com.amazonaws:aws-java-sdk-s3:1.12.117'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    //test email
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    implementation 'org.json:json:20210307'

    // JWT
    //security
    implementation  'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly     'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly     'io.jsonwebtoken:jjwt-jackson:0.12.3'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'io.hypersistence:hypersistence-utils-hibernate-60:3.0.1'

    // Spring Boot Starter Data Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // Redis Client
    // Spring Cache Abstraction
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compileJava.options.encoding = 'UTF-8'

//    //new security
//    implementation("commons-io:commons-io:2.11.0")


}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

spotless {
    java {
        palantirJavaFormat()
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
