package com.dentalstack.patient.feature.treatmenttracking.enums;

public enum ChatEventType {
    ALIGNER_CHANGED,
    ALIGNER_REVIEW_SUBMITTED,
    ISSUE_REPORTED,
    PHOTO_UPLOADED,

    WEAR_DAYS_EXTENDED_CURRENT,
    WEAR_DAYS_EXTENDED_ALL,
    ALIGNER_STAGE_MOVED,
    WEAR_DAYS_REVERTED,

    TREATMENT_PLAN_CREATED,
    TREATMENT_PLAN_APPROVED,
    TREATMENT_PLAN_REVISION_REQUESTED,
    NEW_TREATMENT_STARTED
}
