package com.dentalstack.patient.global.exception;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum BusinessErrorCode {
    ALIGNER_JOURNEY_NOT_FOUND("PA001"),
    PATIENT_INVITATION_ALREADY_EXISTS("PI001"),
    PATIENT_ALREADY_ASSIGNED_TO_DOCTOR("PI002"),
    ACTIVE_ALIGNER_JOURNEY_FOUND("PI003"),
    PAUSED_ALIGNER_JOURNEY_FOUND("PI004"),
    ALIGNER_JOURNEY_DEACTIVATED("PI005"),

    REMINDER_ALREADY_EXISTS("PR001"),
    FAILED_SCHEDULE_REMINDER("PR002"),

    ALIGNER_PRODUCTION_LAB_NOT_FOUND("AL001"),
    NO_ACTIVE_ALIGNER_PRODUCTION_ORDER_FOUND("AL002"),
    ALIGNER_PRODUCTION_ALREADY_EXISTS("AL003"),

    ALIGNER_PRODUCTION_REMINDER_NOT_FOUND("APR001"),

    NOTE_NOT_FOUND("AN001"),

    ALREADY_INVITED("AI001"),
    FAILED_TO_GENERATE_INVITATION_CODE("AI002"),
    INVALID_INVITE_CODE("AI003"),
    INVITATION_NOT_FOUND("AI004"),
    BRACE_PATIENT_FOUND("AI004"),

    DOCTOR_NOT_FOUND("DI001"),

    APPOINTMENT_NOT_FOUND("AP001"),
    APPOINTMENT_REMINDER_NOT_FOUND("AP002"),
    APPOINTMENT_ALREADY_EXISTS("AP003"),
    APPOINTMENT_REMINDER_NOT_ADDED("AP004"),
    APPOINTMENT_REMINDER_ALREADY_EXIST("AP005"),

    INVALID_PATH_FOUND("F00001"),
    FILE_ALREADY_EXISTS("F00002"),
    FILES_NOT_SUPPORTED("F00003"),
    FILE_NOT_FOUND("F00004"),
    FAILED_TO_MOVE("F00005"),
    NOT_A_FOLDER("F00006"),
    FILE_OPERATION_NOT_ALLOWED("F00007"),
    FAILED_DOWNLOAD_FILE("F00008"),

    BRACES_NOT_FOUND("BR0001"),

    PAYMENT_NOT_FOUND("PY0001"),

    TREATMENT_NOT_FOUND("T0001"),
    INCORRECT_TREATMENT_COST("T00002"),

    REMINDER_NOT_FOUND("RM0001"),
    REMINDER_ALREADY_TRIGGERED("RM0002"),

    BAD_REQUEST("400"),

    MATERIAL_ALREADY_PRESENT("M00001"),
    BRACKET_NAME_ALREADY_PRESENT("M00001"),

    ACTIVE_TREATMENT_PLAN_FOUND("TP0001"),
    TREATMENT_PLAN_NOT_FOUND("TP0002"),
    CAN_NOT_PAUSE_RESUME("TP0002"),

    DUPLICATE_NAME_FOUND("TP0004"),

    TRACKING_NOT_FOUND("TR0001"),
    CUSTOMER_PATIENT_TRACKING_ENABLED("TR0002"),

    ALIGNER_ACTION_NOT_FOUND("AC0001"),

    SUBSCRIPTION_NOT_FOUND("SP0001"),
    SUBSCRIPTION_EXTENSION("SP0002"),
    PATIENT_LIMIT_EXCEEDED("SP0003"),
    STORAGE_LIMIT_EXCEEDED("SP0004"),

    ORDER_NOT_FOUND("OR0001"),
    APP_NAME_ALREADY_EXISTS("OR0002"),
    ORG_NAME_MISMATCH("ORG0001"),
    OWNER_DOCTOR_ACCESS_DENIED("ORG0002"),
    ORDER_LIMIT_EXCEEDED("END000"),

    PRACTICE_LOCATION_NOT_FOUND("PL0001"),
    FORBIDDEN("AD0001"),

    MANUFACTURING_NOT_FOUND("MD0001"),
    CASE_RECORD_ALREADY_EXISTS("CR0001"),
    CASE_RECORD_NOT_FOUND("CR0002"),
    ALREADY_EXISTING_PATIENT_OVERVIEW_NOT_AVAILABLE("AEO0001"),
    INVALID_ORDER_STATUS("OS0001"),

    INVITATION_ALREADY_PRESENT_EMAIL("IE0001"),
    DOCTOR_INVITATION_NOT_FOUND("DI0001"),
    INVITATION_ALREADY_PRESENT_MOBILE("IM0001"),
    BAD_INVITATION_REQUEST("BI0001"),
    INVITATION_EMAIL_USED_BY_PATIENT("IE0002"),
    INVITATION_MOBILE_USED_BY_PATIENT("IM0002"),

    SHIPPING_DETAILS_NOT_FOUND("SD0001"),
    ACCESS_CONTROL_EXCEPTION("AC0002"),
    ALIGNER_WEAR_TIME_SESSION_EXCEPTION("AW0001"),
    GENERIC_EXCEPTION("GE0001"),
    SMART_BOX_EXCEPTION("SB0001"),
    COMMENTS_REQUIRED("WF001"),
    NO_TREATMENT_PLAN_AVAILABLE("WF002"),
    NO_PENDING_PLAN("WF003"),
    NO_ACTIVE_PLAN_REVISION("WF004"),
    NO_ACTIVE_PLAN("WF005"),
    NO_ACTIVE_PLAN_STL("WF006"),
    INVALID_REVISION_FROM_CLOSED_OR_APPROVED("WF008"),
    NO_TREATMENT_PLAN_APPROVED("WF009"),
    WORKFLOW_NOT_FOUND("WF010"),
    PATIENT_TASK_NOT_FOUND("WFT001"),
    CANNOT_MOVE_TASK("GE0001"),
    WORKFLOW_STATUS_NOT_FOUND("WFS001"),

    NO_VALID_ORDER_DONE("WF007"),
    NO_PLANS_READY_FOR_REVIEW("WF011"),
    NO_PLANS_TO_REVISE("WF012"),
    NO_PLANS_TO_APPROVE("WF013"),

    SERVICE_PRODUCT_DELETE("AE0001"),

    SERVICE_PRODUCT_ENABLE_CONSTRAINT_VIOLATION("AEE002"),

    CONSENT_TEMPLATE_NOT_FOUND("CT0001"),
    DEFAULT_CONSENT_TEMPLATE_NOT_FOUND("CT0002"),
    INACTIVE_CONSENT_TEMPLATE("CT0003"),
    DIFFERENT_ORG("ORG0002");

    private final String code;

    @JsonValue
    public String getCode() {
        return code;
    }
}
