export const SIGNUP_ORGANIZATION_OPTIONS = [
  'SYNAPSE',
  'ROUTETOSMILE',
  'CRAFTALIGN',
  'SMILEZY',
  'DENTALSTACK',
  'EVOLVALIGN',
  'ALIGNEAZY',
  'CLEARCASTLE',
  'SMILEXCEL',
  'AIIQALIGNER',
] as const;

export const SIGNUP_ROLE_OPTIONS = [
  'CONSULTING_ORTHODONTIST',
  'CLINIC_OWNER',
  'IN_OFFICE_MANUFACTURER',
  'ALIGNER_COMPANY_OR_LAB',
  'COMMERCIAL_ALIGNER_LAB',
  'LAB_STAFF',
  'CUSTOMER',
  'VENDOR',
  'PRACTICE',
  'ENTERPRISE_COMPANY_LAB',
  'INTERNAL_USER',
] as const;
