package com.dental_stack.notification.enums;

public enum NotificationEventType {
    ORDER_UNPROCESSED_DUE,
    SUBSCRIPTION_TRIAL_EXPIRING,
    SUBSCRIPTION_TRIAL_EXPIRED,
    SUBSCRIPTION_PAID_PLAN_EXPIRED,
    SUBSCRIPTION_PAID_PLAN_RENEWAL,
    PATIENT_ASSIGNED_TO_PRACTICE,
    PATIENT_CONSOLIDATED_REPORT,
    WHATSAPP_MESSAGE_SENT,
    SEND_NOTIFICATION
}
